server:
  ingress:
    enabled: true
    hosts:
      - argocd.${hosted_zone_name}
    annotations:
        kubernetes.io/ingress.class: traefik-ext-${env}
        external-dns.alpha.kubernetes.io/target: traefik-ext.${hosted_zone_name}
  extraArgs:
    - "--insecure"
  config:
    url: https://argocd.${hosted_zone_name}
  additionalApplications:
    - name: seed-job
      namespace: default
      project: default
      source:
        repoURL: git@github.com:Dgadavin/k8s-manifests.git
        targetRevision: HEAD
        path: argocd-jobs/${env}
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: default
